server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agriconnect_users}
    username: ${DB_USERNAME:agri_user}
    password: ${DB_PASSWORD:agri_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.agriconnect.*"

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckFncmlDb25uZWN0QXBwbGljYXRpb24yMDI2}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:agriconnect-storage}
    region: ${AWS_S3_REGION:eu-west-1}
    access-key: ${AWS_ACCESS_KEY_ID:dev}
    secret-key: ${AWS_SECRET_ACCESS_KEY:dev}
  cdn:
    base-url: ${CDN_BASE_URL:http://localhost:4566}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.agriconnect: DEBUG
