package com.agriconnect.notification.domain.enums;

public enum NotificationType {
    // Auth
    OTP_SENT,
    // KYC
    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,
    // Labor
    JOB_APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    CONTRACT_GENERATED,
    CONTRACT_SIGNED,
    MISSION_STARTED,
    MISSION_COMPLETED,
    MISSION_DISPUTED,
    MISSION_DISPUTE_RESOLVED,
    // Marketplace
    ORDER_CONFIRMED,
    ORDER_PREPARING,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    // Payment
    TOPUP_SUCCESS,
    TOPUP_FAILED,
    PAYMENT_RECEIVED,
    WITHDRAWAL_SUCCESS,
    WITHDRAWAL_FAILED,
    ESCROW_LOCKED,
    ESCROW_RELEASED,
    // Reviews
    NEW_REVIEW_RECEIVED,
    // System
    ACCOUNT_VERIFIED,
    SYSTEM_ALERT,
    PROMOTIONAL
}
